### ISSUE TITLE
Add support for Contrast results

### ISSUE THREAD

**Issue by nahsra** [pixee/upload-tool-results-action#16]
We need to add support for Contrast results. The file to be uploaded is expected to be an XML export from Contrast Assess.

Here's some example code for pulling the data:
```bash
curl -o findings.zip -H "Accept: application/x-zip-compressed" -H "Authorization: <AUTH_TOKEN>" -H "API-Key: <API_KEY>" -H "Content-Type: application/json" -X POST https://apptwo.contrastsecurity.com/Contrast/api/ng/<ORG_ID>/traces/<APP_ID>/export/xml/all
```

Note that this creates a `findings.zip` file that will contain a single file containing all the vulnerabilities, e.g.: `vulnerabilities2024<YEAR-MONTH-DAY.xml`.

**Comment by carlosu7** [comment]
@nahsra is this PR related to this? https://github.com/pixee/upload-tool-results-action/pull/17

**Comment by nahsra** [comment]
Yes @drdavella added support for uploading the file directly, but we still need to create the ability for users to pull the data natively like we do with Sonar.
